name: gh_project
channels:
  - conda-forge
  - defaults
dependencies:
  - black
  - bump2version
  - notebook
  - pip
  - pytest
  - python >=3.7,<3.9
  - requests>=2.24.0
  - pip:
      - python-frontmatter
