name: Pages

on:
  push:
    branches:
    - main
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for manually running CI Build workflow
        required: False
        default: ''
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-python@v2
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Python info
      run: |
        which python
        python --version
    - name: Build package and create dev environment
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]
    - name: Build and Commit
      uses: sphinx-notes/pages@v2
      with: 
        documentation_path: docs/source
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
