name: Build and test Python package

on:
  push:
  pull_request:
    types: [opened, reopened]

jobs:
  build_pypi:
    name: Test pypi build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python info
        run: |
          which python
          python --version
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
      - name: Build package
        run: |
          pip install wheel twine
          python setup.py sdist bdist_wheel
      - name: Check package
        run: |
          python -m twine check dist/*
      - name: Install package
        run: |
          pip install -e .[dev]
      - name: Show pip list again
        run: |
          pip list
      - name: Run tests
        run: |
          pytest
